[2022-09-04T16:45:02.905+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_airflow_dag.save_datetime scheduled__2022-09-04T16:44:00+00:00 [queued]>
[2022-09-04T16:45:02.912+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: first_airflow_dag.save_datetime scheduled__2022-09-04T16:44:00+00:00 [queued]>
[2022-09-04T16:45:02.913+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-04T16:45:02.914+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-04T16:45:02.915+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-04T16:45:02.923+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): save_datetime> on 2022-09-04 16:44:00+00:00
[2022-09-04T16:45:02.929+0000] {standard_task_runner.py:52} INFO - Started process 271 to run task
[2022-09-04T16:45:02.932+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_***_dag', 'save_datetime', 'scheduled__2022-09-04T16:44:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp219_c6dp', '--error-file', '/tmp/tmpcv3aj17c']
[2022-09-04T16:45:02.934+0000] {standard_task_runner.py:80} INFO - Job 17: Subtask save_datetime
[2022-09-04T16:45:02.978+0000] {task_command.py:371} INFO - Running <TaskInstance: first_airflow_dag.save_datetime scheduled__2022-09-04T16:44:00+00:00 [running]> on host a8d8517a6bff
[2022-09-04T16:45:03.019+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_***_dag
AIRFLOW_CTX_TASK_ID=save_datetime
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T16:44:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T16:44:00+00:00
[2022-09-04T16:45:03.027+0000] {logging_mixin.py:115} INFO - [{'year': 2022, 'month': 'Sep', 'day': 4, 'time': '16:45:01', 'day_of_week': 'Sun'}]
[2022-09-04T16:45:03.035+0000] {logging_mixin.py:115} INFO - /Users/hugomufraggi/dev/seed-test
[2022-09-04T16:45:03.042+0000] {logging_mixin.py:115} INFO -    year month  day      time day_of_week
0  2022   Sep    4  16:45:01         Sun
[2022-09-04T16:45:03.044+0000] {logging_mixin.py:115} INFO - False
[2022-09-04T16:45:03.047+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_dag.py", line 45, in save_datetime
    df.to_csv(csv_path, index=False, mode=df_mode, header=df_header)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hugomufraggi/dev/seed-test'
[2022-09-04T16:45:03.057+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=first_***_dag, task_id=save_datetime, execution_date=20220904T164400, start_date=20220904T164502, end_date=20220904T164503
[2022-09-04T16:45:03.064+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 17 for task save_datetime ([Errno 2] No such file or directory: '/Users/hugomufraggi/dev/seed-test'; 271)
[2022-09-04T16:45:03.108+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-04T16:45:03.132+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
